### ISSUE TITLE
Rebrand the project to Cider

### ISSUE THREAD

**Issue by aaronsky** [cidertool/cider#10]
This issue has two distinct elements: a new name, and a logo.

## Name

I've decided that I don't love applereleaser as a name long-term. It's bland, it's too many syllables, and I don't want to give folks the impression this is affiliated with Apple. Here are the criteria I'm laying out for a new name:

1. It should stay away from the release, ship, or submission motifs (too similar to goreleaser, spaceship, etc) unless it's a really good pitch.
1. It must be three or less (ideally two) syllables, so it's easier for folks to remember it. 
1. Stay away from initialisms, acronyms, or abbreviations unless it's a really good pitch.
1. It shouldn't give off an impression that this is endorsed by Apple.

Some examples of other good tool names in the Apple dev OSS ecosystem:

* Spaceship
* Fastlane
* SwiftGen
* Swiftlint
* Mint
* SourceKit

## Logo

1. The logo should compliment the name and the app, by being simple and flexible.
1. It should scale well to different sizes
1. The logo should avoid Apple, Go "gopher", iPhone, or App Store motifs unless they can be integrated subtly and remixed in compliance with Apple's [brand guidelines](https://www.apple.com/shop/Catalog/US/Images/affiliates/affiliate-banners-guide.pdf) and fair use. 

Requested assets:

* Navigation header for docs site
* favicon.ico for docs site
* square image ~150px high version for README.md

**Comment by reccanti** [comment]
Kraken – as in "Release the Kraken"

**Comment by reccanti** [comment]
Snapple – "Makes releasing Apple apps a snap!"

**Comment by reccanti** [comment]
Dunk – I just think it's a nice image. Like, as the final stage of your application, you're doing a slam-dunk

**Comment by reccanti** [comment]
Nimbus – Has a "sky" theme

**Comment by reccanti** [comment]
Pelican – Also "sky" themed. Named after the [Pelican mailman from Animal Crossing](https://animalcrossing.fandom.com/wiki/Pete)

**Comment by reccanti** [comment]
Norman/Porter – "delivery" themed. Reference to Norman Reedus's character in Death Stranding

**Comment by reccanti** [comment]
Livia – Named after part of the [scientific name for Carrier Pigeons](https://en.wikipedia.org/wiki/Homing_pigeon)

**Comment by aaronsky** [comment]
Cider

Explanation

* Kids giving their teachers apples or potatoes as a token in exchange for their education is a decent analogy for devs being required to pay tribute in order to be listed on the App Store
* Those apples were commonly used for cider back in those days because it was cleaner than water

Cons

* https://github.com/cider is taken, but it hasn't been updated since 2014
* There are other projects in ObjC/Swift named Cider, with varying degrees of activity
  * https://github.com/search?l=Objective-C&q=cider&type=Repositories
  * https://github.com/search?l=Swift&q=cider&type=Repositories

**Comment by aaronsky** [comment]
The name Cider has been taken under consideration. Branding work is happening on #24.

**Comment by aaronsky** [comment]
Splitting out remaining asset development work into the new ticket #26
